name: cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Gcloud build
        run: gcloud builds submit --tag europe-west9-docker.pkg.dev/notely-429921/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west9-docker.pkg.dev/notely-429921/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-429921 --max-instances=4